ArkEcosystem/python-client

.gitignore
README.md
setup.cfg
setup.py

Added `.gitignore` so we don't commit random stuff to this repository.
I've added `dev` and `test` section to `setup.py` so for installing dev or test on your machine or on travis, you would just do `pip install .[dev]` or `pip install .[test]` and it will correctly install everything for you.

Added test, dev and install requirements

---

README.md

Written up this little guide for contributing just so we are consistent with our code.

Add "Guide for contributing" section to the readme

---

ark/one/account.py
ark/one/api.py
ark/one/delegate.py
ark/one/signature.py
ark/one/transaction.py
ark/one/transport.py
ark/one/vote.py

Renamed method and parameter names to meet PEP8 format. See [this](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

Renamed functions to meet PEP8 format.

---

README.md

Adds a link to the official documentation as all other repositories have.

chore: add docs link & codecov badge to readme

---

.coveragerc
.gitignore
.travis.yml
ark/api/two/transactions.py
setup.py

Adding code coverage reports.
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
None

Add code coverage

---

ark/api/two/transactions.py
tests/api/two/test_transactions.py

The endpoint is expecting data in a different format.
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
None

Fix method for sending transactions

---

README.md

Fix the link to the documentation site.

update link documentation in site

---

README.md

This pull request applies the badge style outlined in https://github.com/ArkEcosystem/boilerplate and fixes the `All Contributors` link.

chore: fixes badges / contributors link in readme

---

.gitignore

Added .vs and .vscode to the .gitignore file to support Visual Studio and VS Code
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
Fixes #35

chore: Add Visual Studio and VS Code Support

---

.travis.yml
Makefile

Update the 'py.test' syntax to use 'pytest' for better cross-platform support.
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
Fixes #39

chore: update pytest syntax

---

.circleci/config.yml
.coveragerc

Adds Codecov to CircleCI config.

chore: add codecov to circleci config

---

client/connection.py
setup.py
tests/test_connection.py

Make api requests more resilient using a full jitter backoff strategy

Request retry mechanism

---

tests/test_connection.py

Add tests for request retry mechanism

Add tests for retrying requests

---

client/api/two/wallets.py
tests/api/two/test_wallets.py

Implements the `/wallets/top` API in the Python SDK, in order to bring the "wallets" APIs to parity with the reference (JavaScript) client.
_Let me know if this needs any form documentation. I've excluded it for now, just on precedent with other APIs implemented here._
N/A

feat(client): implement top wallets API

---

client/connection.py

remove lib not used

---

client/api/node.py
tests/api/test_node.py

Adds the new `node/fees` API endpoint.

feat: add node/fees endpoint

---

client/api/node.py
tests/api/test_node.py

Adds the `node/configuration/crypto` endpoint.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:

feat: crypto endpoint

---

.codacy.yaml
client/api/rounds.py
tests/api/test_rounds.py

Adds the `rounds/{id}/delegates` endpoint.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:

feat: add rounds api

---

client/api/bridgechains.py
client/api/businesses.py
client/api/locks.py
client/api/wallets.py
tests/api/test_bridgechains.py
tests/api/test_businesses.py
tests/api/test_locks.py
tests/api/test_wallets.py

Adds the following API endpoints
**GET**
**POST**

feat: 2.6 api endpoints

---

client/api/blocks.py
tests/api/test_blocks.py

Adds methods for the `blocks/first` and `blocks/last` endpoints.

feat: add methods for first and last block

---

client/api/bridgechains.py
client/api/businesses.py
tests/api/test_bridgechains.py
tests/api/test_businesses.py

Moves the `bridgechains/{id}` endpoint to the businesses resource.

chore: move bridgechain show endpoint
